name: Run tests and upload coverage

on: 
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Check Jest install (debug)
        run: |
          ls -l node_modules/.bin/jest
          node_modules/.bin/jest --version

      - name: Run tests with coverage
        run: node_modules/.bin/jest --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
